version: '3.7'

services:
  php74-function:
    container_name: ${ARCHITECTURE}-php74-function
    image: bref/${ARCHITECTURE}-php74-function
    build:
      context: ..
      dockerfile: runtime/docker/function.Dockerfile
      args:
        - AWS_TAG
        - ARCHITECTURE
        - PHP_VERSION=php74
    command: /tests/integration/fixture_function.php
    environment:
      - PHP_INI_SCAN_DIR=/opt/php-ini
      - PHP_VERSION=php74
    working_dir: /tests
    volumes:
      - ./tests:/tests
      - ./tests/integration/fixture_php.ini:/var/task/php/conf.d/fixture_php.ini

  php74-function-tester:
    container_name: ${ARCHITECTURE}-php74-function-tester
    image: bref/${ARCHITECTURE}-php74-function
    entrypoint: /opt/bin/php
    command: /tests/integration/test_invoke_function.php
    environment: [PHP_INI_SCAN_DIR=/opt/php-ini]
    working_dir: /tests
    links: [php74-function:php-function]
    volumes:
      - ./tests:/tests

  php74-function-zip:
    image: bref/${ARCHITECTURE}-php74-function-zip
    build:
      args:
        IMAGE: bref/${ARCHITECTURE}-php74-function
      context: ..
      dockerfile: runtime/publish/Zip.Dockerfile
    entrypoint: /bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/function/php74-function-layer.zip"]
    volumes:
      - /tmp/bref-zip/:/tmp/bref-zip/

###############################

  php80-function:
    container_name: ${ARCHITECTURE}-php80-function
    image: bref/${ARCHITECTURE}-php80-function
    build:
      context: ..
      dockerfile: runtime/docker/function.Dockerfile
      args:
        - AWS_TAG
        - ARCHITECTURE
        - PHP_VERSION=php80
    command: /tests/integration/fixture_function.php
    environment:
      - PHP_INI_SCAN_DIR=/opt/php-ini
      - PHP_VERSION=php80
    working_dir: /tests
    volumes:
      - ./tests:/tests
      - ./tests/integration/fixture_php.ini:/var/task/php/conf.d/fixture_php.ini

  php80-function-tester:
    container_name: ${ARCHITECTURE}-php80-function-tester
    image: bref/${ARCHITECTURE}-php80-function
    entrypoint: /opt/bin/php
    command: /tests/integration/test_invoke_function.php
    environment: [PHP_INI_SCAN_DIR=/opt/php-ini]
    working_dir: /tests
    links: [php80-function:php-function]
    volumes:
      - ./tests:/tests

  php80-function-zip:
    image: bref/${ARCHITECTURE}-php80-function-zip
    build:
      args:
        IMAGE: bref/${ARCHITECTURE}-php80-function
      context: ..
      dockerfile: runtime/publish/Zip.Dockerfile
    entrypoint: /bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/function/php80-function-layer.zip"]
    volumes:
      - /tmp/bref-zip/:/tmp/bref-zip/

###############################

  php81-function:
    container_name: ${ARCHITECTURE}-php81-function
    image: bref/${ARCHITECTURE}-php81-function
    build:
      context: ..
      dockerfile: runtime/docker/function.Dockerfile
      args:
        - AWS_TAG
        - ARCHITECTURE
        - PHP_VERSION=php81
    command: /tests/integration/fixture_function.php
    environment:
      - PHP_INI_SCAN_DIR=/opt/php-ini
      - PHP_VERSION=php81
    working_dir: /tests
    volumes:
      - ./tests:/tests
      - ./tests/integration/fixture_php.ini:/var/task/php/conf.d/fixture_php.ini

  php81-function-tester:
    container_name: ${ARCHITECTURE}-php81-function-tester
    image: bref/${ARCHITECTURE}-php81-function
    entrypoint: /opt/bin/php
    command: /tests/integration/test_invoke_function.php
    environment: [PHP_INI_SCAN_DIR=/opt/php-ini]
    working_dir: /tests
    links: [php81-function:php-function]
    volumes:
      - ./tests:/tests

  php81-function-zip:
    image: bref/${ARCHITECTURE}-php81-function-zip
    build:
      args:
        IMAGE: bref/${ARCHITECTURE}-php81-function
      context: ..
      dockerfile: runtime/publish/Zip.Dockerfile
    entrypoint: /bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/function/php81-function-layer.zip"]
    volumes:
      - /tmp/bref-zip/:/tmp/bref-zip/