version: '3.8'

services:

#### PHP 8.0

  build-php-80:
    image: bref/build-${CPU_PREFIX}php-80
    build:
      context: .
      dockerfile: php-80/cpu-${CPU}.Dockerfile
      target: build-environment


  php-80:
    image: bref/${CPU_PREFIX}php-80
    build:
      context: .
      dockerfile: php-80/cpu-${CPU}.Dockerfile
      target: function

  php-80-zip:
    image: bref/${CPU_PREFIX}php-80-zip
    build:
      context: .
      dockerfile: php-80/cpu-${CPU}.Dockerfile
      target: zip-function
    entrypoint: /bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/${CPU_PREFIX}php-80.zip"]
    volumes:
      - ./output:/tmp/bref-zip


  php-80-fpm:
    image: bref/${CPU_PREFIX}php-80-fpm
    build:
      context: .
      dockerfile: php-80/cpu-${CPU}.Dockerfile
      target: fpm

  php-80-zip-fpm:
    image: bref/${CPU_PREFIX}php-80-fpm-zip
    build:
      context: .
      dockerfile: php-80/cpu-${CPU}.Dockerfile
      target: zip-fpm
    entrypoint: /bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/${CPU_PREFIX}php-80-fpm.zip"]
    volumes:
      - ./output:/tmp/bref-zip


  php-80-console:
    image: bref/${CPU_PREFIX}php-80-console
    build:
      context: ./layers/console
      target: console
      args:
        PHP_VERSION: 80
        CPU_PREFIX: ${CPU_PREFIX}

  php-80-zip-console:
    image: bref/${CPU_PREFIX}php-80-console-zip
    build:
      context: ./layers/console
      target: zip-console
      args:
        PHP_VERSION: 80
        CPU_PREFIX: ${CPU_PREFIX}
    entrypoint: /bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/${CPU_PREFIX}console.zip"]
    volumes:
      - ./output:/tmp/bref-zip


#### PHP 8.1

  build-php-81:
    image: bref/build-${CPU_PREFIX}php-81
    build:
      context: .
      dockerfile: php-81/cpu-${CPU}.Dockerfile
      target: build-environment


  php-81:
    image: bref/${CPU_PREFIX}php-81
    build:
      context: .
      dockerfile: php-81/cpu-${CPU}.Dockerfile
      target: function

  php-81-zip:
    image: bref/${CPU_PREFIX}php-81-zip
    build:
      context: .
      dockerfile: php-81/cpu-${CPU}.Dockerfile
      target: zip-function
    entrypoint: /bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/${CPU_PREFIX}php-81.zip"]
    volumes:
      - ./output:/tmp/bref-zip


  php-81-fpm:
    image: bref/${CPU_PREFIX}php-81-fpm
    build:
      context: .
      dockerfile: php-81/cpu-${CPU}.Dockerfile
      target: fpm

  php-81-zip-fpm:
    image: bref/${CPU_PREFIX}php-81-fpm-zip
    build:
      context: .
      dockerfile: php-81/cpu-${CPU}.Dockerfile
      target: zip-fpm
    entrypoint: /bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/${CPU_PREFIX}php-81-fpm.zip"]
    volumes:
      - ./output:/tmp/bref-zip


  php-81-console:
    image: bref/${CPU_PREFIX}php-81-console
    build:
      context: ./layers/console
      target: console
      args:
        PHP_VERSION: 81
        CPU_PREFIX: ${CPU_PREFIX}


#### PHP 8.2

  build-php-82:
    image: bref/build-${CPU_PREFIX}php-82
    build:
      context: .
      dockerfile: php-82/cpu-${CPU}.Dockerfile
      target: build-environment


  php-82:
    image: bref/${CPU_PREFIX}php-82
    build:
      context: .
      dockerfile: php-82/cpu-${CPU}.Dockerfile
      target: function

  php-82-zip:
    image: bref/${CPU_PREFIX}php-82-zip
    build:
      context: .
      dockerfile: php-82/cpu-${CPU}.Dockerfile
      target: zip-function
    entrypoint: /bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/${CPU_PREFIX}php-82.zip"]
    volumes:
      - ./output:/tmp/bref-zip


  php-82-fpm:
    image: bref/${CPU_PREFIX}php-82-fpm
    build:
      context: .
      dockerfile: php-82/cpu-${CPU}.Dockerfile
      target: fpm

  php-82-zip-fpm:
    image: bref/${CPU_PREFIX}php-82-fpm-zip
    build:
      context: .
      dockerfile: php-82/cpu-${CPU}.Dockerfile
      target: zip-fpm
    entrypoint: /bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/${CPU_PREFIX}php-82-fpm.zip"]
    volumes:
      - ./output:/tmp/bref-zip


  php-82-console:
    image: bref/${CPU_PREFIX}php-82-console
    build:
      context: ./layers/console
      target: console
      args:
        PHP_VERSION: 82
        CPU_PREFIX: ${CPU_PREFIX}
