version: "3.7"

services:
  eu-west-1:
    image: amazon/aws-cli
    entrypoint: /bin/bash
    command: /publish.sh
    environment:
      - AWS_PROFILE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - ARCHITECTURE
      - PHP_VERSION
      - TYPE
      - REGION=eu-west-1
    volumes:
      - ./publish/publish.sh:/publish.sh
      - ~/.aws:/root/.aws
      - /tmp/bref-zip/:/tmp/bref-zip/

  eu-west-2:
    image: amazon/aws-cli
    entrypoint: /bin/bash
    command: /publish.sh
    environment:
      - AWS_PROFILE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - ARCHITECTURE
      - PHP_VERSION
      - TYPE
      - REGION=eu-west-2
    volumes:
      - ./publish/publish.sh:/publish.sh
      - ~/.aws:/root/.aws
      - /tmp/bref-zip/:/tmp/bref-zip/

  eu-central-1:
    image: amazon/aws-cli
    entrypoint: /bin/bash
    command: /publish.sh
    environment:
      - AWS_PROFILE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - ARCHITECTURE
      - PHP_VERSION
      - TYPE
      - REGION=eu-central-1
    volumes:
      - ./publish/publish.sh:/publish.sh
      - ~/.aws:/root/.aws
      - /tmp/bref-zip/:/tmp/bref-zip/

