version: "3.7"

services:
  zip:
    image: ${IMAGE}-zip
    build:
      args:
        - IMAGE=${IMAGE}
      context: ..
      dockerfile: runtime/publish/Zip.Dockerfile
    entrypoint: /usr/bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/${TYPE}/${LAYER}-layer.zip"]
    volumes:
      - /tmp/bref-zip/:/tmp/bref-zip/

  publish:
    image: amazon/aws-cli
    entrypoint: /bin/bash
    command: /publish.sh
    environment:
      - AWS_PROFILE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - IMAGE
      - LAYER
      - BUCKET
      - REGION
    volumes:
      - ./publish/publish.sh:/publish.sh
      - ~/.aws:/root/.aws
      - /tmp/bref-zip/:/tmp/bref-zip/