version: '3.7'

services:
  php74-slim:
    container_name: ${ARCHITECTURE}-php74-slim
    image: bref/${ARCHITECTURE}-php74-slim
    build:
      context: ..
      dockerfile: runtime/docker/slim.Dockerfile
      args:
        - AWS_TAG
        - ARCHITECTURE
        - PHP_VERSION=php74
    command: /tests/integration/fixture_function.php
    environment:
      - PHP_INI_SCAN_DIR=/opt/php-ini
      - PHP_VERSION=php74
    working_dir: /tests
    volumes:
      - ./tests:/tests
      - ./tests/integration/fixture_php.ini:/var/task/php/conf.d/fixture_php.ini

  php74-slim-tester:
    container_name: ${ARCHITECTURE}-php74-slim-tester
    image: bref/${ARCHITECTURE}-php74-slim
    entrypoint: /opt/bin/php
    command: /tests/integration/test_invoke_slim.php
    environment: [PHP_INI_SCAN_DIR=/opt/php-ini]
    working_dir: /tests
    links:
      - php74-slim:php-slim
    volumes:
      - ./tests:/tests

  php74-slim-zip:
    image: bref/${ARCHITECTURE}-php74-slim-zip
    build:
      args:
        IMAGE: bref/${ARCHITECTURE}-php74-slim
      context: ..
      dockerfile: runtime/publish/Zip.Dockerfile
    entrypoint: /bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/slim/php74-slim-layer.zip"]
    volumes:
      - /tmp/bref-zip/:/tmp/bref-zip/

#######################################

  php80-slim:
    container_name: ${ARCHITECTURE}-php80-slim
    image: bref/${ARCHITECTURE}-php80-slim
    build:
      context: ..
      dockerfile: runtime/docker/slim.Dockerfile
      args:
        - AWS_TAG
        - ARCHITECTURE
        - PHP_VERSION=php80
    command: /tests/integration/fixture_function.php
    environment:
      - PHP_INI_SCAN_DIR=/opt/php-ini
      - PHP_VERSION=php80
    working_dir: /tests
    volumes:
      - ./tests:/tests
      - ./tests/integration/fixture_php.ini:/var/task/php/conf.d/fixture_php.ini

  php80-slim-tester:
    container_name: ${ARCHITECTURE}-php80-slim-tester
    image: bref/${ARCHITECTURE}-php80-slim
    entrypoint: /opt/bin/php
    command: /tests/integration/test_invoke_slim.php
    environment: [PHP_INI_SCAN_DIR=/opt/php-ini]
    working_dir: /tests
    links:
      - php80-slim:php-slim
    volumes:
      - ./tests:/tests

  php80-slim-zip:
    image: bref/${ARCHITECTURE}-php80-slim-zip
    build:
      args:
        IMAGE: bref/${ARCHITECTURE}-php80-slim
      context: ..
      dockerfile: runtime/publish/Zip.Dockerfile
    entrypoint: /bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/slim/php80-slim-layer.zip"]
    volumes:
      - /tmp/bref-zip/:/tmp/bref-zip/

#######################################

  php81-slim:
    container_name: ${ARCHITECTURE}-php81-slim
    image: bref/${ARCHITECTURE}-php81-slim
    build:
      context: ..
      dockerfile: runtime/docker/slim.Dockerfile
      args:
        - AWS_TAG
        - ARCHITECTURE
        - PHP_VERSION=php81
    command: /tests/integration/fixture_function.php
    environment:
      - PHP_INI_SCAN_DIR=/opt/php-ini
      - PHP_VERSION=php81
    working_dir: /tests
    volumes:
      - ./tests:/tests
      - ./tests/integration/fixture_php.ini:/var/task/php/conf.d/fixture_php.ini

  php81-slim-tester:
    container_name: ${ARCHITECTURE}-php81-slim-tester
    image: bref/${ARCHITECTURE}-php81-slim
    entrypoint: /opt/bin/php
    command: /tests/integration/test_invoke_slim.php
    environment: [PHP_INI_SCAN_DIR=/opt/php-ini]
    working_dir: /tests
    links:
      - php81-slim:php-slim
    volumes:
      - ./tests:/tests

  php81-slim-zip:
    image: bref/${ARCHITECTURE}-php81-slim-zip
    build:
      args:
        IMAGE: bref/${ARCHITECTURE}-php81-slim
      context: ..
      dockerfile: runtime/publish/Zip.Dockerfile
    entrypoint: /bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/slim/php81-slim-layer.zip"]
    volumes:
      - /tmp/bref-zip/:/tmp/bref-zip/