name: Build

on:
    push:
        branches: [ 'main' ]
    pull_request:
        branches: [ '*' ]

jobs:
    build:
        name: Building images and layers
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: make layers
