name: Build

on:
    push:
        branches: [ 'main' ]
    pull_request:
        branches: [ '*' ]

jobs:
    build-x86:
        name: Building x86 images and layers
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: make -f cpu-x86.Makefile layers

    build-arm:
        name: Building ARM images and layers
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: make -f cpu-arm.Makefile layers
