name: Update base-devel images

on:
    # This workflow can be manually triggered
    workflow_dispatch:
    schedule:
        # Once a week
        -   cron: '0 0 * * 0'

jobs:
    publish-base-devel:
        name: Build and publish base-devel
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Log in to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
            # See https://stackoverflow.com/questions/70312490/github-actions-runner-environment-doesnt-build-for-arm-images
            -   name: Set up QEMU to build ARM images
                uses: docker/setup-qemu-action@v2
            -   name: Set up Docker buildx to build ARM images
                uses: docker/setup-buildx-action@v2
            -   run: cd base-devel && make upload-to-docker-hub
