name: Tests

on:
    push:
        branches: [ 'main' ]
    pull_request:
        branches: [ '*' ]

jobs:
    tests:
        name: Build and tests layers
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                cpu:
                    - x86
                    - arm
                php_version:
                    - 80
                    - 81
                    - 82
        steps:
            -   uses: actions/checkout@v3

            -   uses: depot/setup-action@v1

            -   name: Build Docker images
                run: make -f cpu-${{ matrix.cpu }}.Makefile docker-images-php-${{ matrix.php_version }}
                env:
                    DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}

            -   name: Test that layers can be exported
                run: |
                    make -f cpu-${{ matrix.cpu }}.Makefile layer-php-${{ matrix.php_version }}
                    make -f cpu-${{ matrix.cpu }}.Makefile layer-php-${{ matrix.php_version }}-fpm

            -   name: Run tests
                run: make -f cpu-${{ matrix.cpu }}.Makefile test-${{ matrix.php_version }}
