name: Tests

on:
    push:
        branches: [ 'main' ]
    pull_request:
        branches: [ '*' ]

jobs:
    tests-x86:
        name: Build x86 images, layers, and run tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: make -f cpu-x86.Makefile layers
            -   run: make -f cpu-x86.Makefile test

    tests-arm:
        name: Build ARM images, layers, and run tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: make -f cpu-arm.Makefile layers
            -   run: make -f cpu-arm.Makefile test
