name: Tests

on:
    push:
        branches: [ 'main' ]
    pull_request:
        branches: [ '*' ]

jobs:
    tests-x86:
        name: Build x86 images, layers, and run tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: make -f cpu-x86.Makefile layers
            -   run: make -f cpu-x86.Makefile test

    tests-arm:
        name: Build ARM images, layers, and run tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            # See https://stackoverflow.com/questions/70312490/github-actions-runner-environment-doesnt-build-for-arm-images
            -   name: Set up QEMU to build ARM images
                uses: docker/setup-qemu-action@v1
            -   name: Set up Docker buildx to build ARM images
                uses: docker/setup-buildx-action@v1
            -   run: make -f cpu-arm.Makefile layers
            -   run: make -f cpu-arm.Makefile test
