name: Tests

on:
    push:
        branches: [ 'main' ]
    pull_request:
        branches: [ '*' ]

jobs:
    build-base-devel-x86:
        name: Build base-devel-x86
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: docker/setup-buildx-action@v2 # to use BuildKit features
            -   uses: docker/build-push-action@v3
                with:
                    file: base-devel/cpu-x86.Dockerfile
                    tags: bref/base-devel-x86:latest
                    outputs: type=docker,dest=/tmp/base-devel-x86.tar
                    # Cache Docker layers in the GitHub Actions cache
                    # https://docs.docker.com/build/cache/backends/gha/
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
            -   uses: actions/upload-artifact@v3 # Expose /tmp/base-devel-x86.tar to other jobs
                with:
                    name: base-devel-x86
                    path: /tmp/base-devel-x86.tar

    tests-x86:
        name: Build x86 images, layers, and run tests
        needs: build-base-devel-x86
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up Docker buildx to use BuildKit features
                uses: docker/setup-buildx-action@v2
                with:
                    # Sets up `docker build` command as an alias to `docker buildx`
                    install: true
            -   uses: actions/download-artifact@v3
                with:
                    name: base-devel-x86
                    path: /tmp/base-devel-x86.tar
            -   name: Load the bref/base-devel-x86 image
                run: |
                    docker load --input /tmp/base-devel-x86.tar
                    docker image ls -a
            -   run: make -f cpu-x86.Makefile layers
            -   run: make -f cpu-x86.Makefile test

    tests-arm:
        name: Build ARM images, layers, and run tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            # See https://stackoverflow.com/questions/70312490/github-actions-runner-environment-doesnt-build-for-arm-images
            -   name: Set up QEMU to build ARM images
                uses: docker/setup-qemu-action@v2
            -   name: Set up Docker buildx to build ARM images
                uses: docker/setup-buildx-action@v2
            -   run: make -f cpu-arm.Makefile layers
            -   run: make -f cpu-arm.Makefile test
