name: Tests

on:
    push:
        branches: [ 'main' ]
    pull_request:
        branches: [ '*' ]

jobs:
    tests:
        name: Build and tests PHP ${{ matrix.php_version }}, ${{ matrix.cpu }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                cpu:
                    - x86
                    - arm
                php_version:
                    - 80
                    - 81
                    - 82
        steps:
            -   uses: actions/checkout@v3

            # See https://stackoverflow.com/questions/70312490/github-actions-runner-environment-doesnt-build-for-arm-images
            -   name: Set up QEMU to run ARM images (that were built with Depot)
                uses: docker/setup-qemu-action@v2

            -   uses: depot/setup-action@v1

            -   name: Build Docker images
                run: make docker-images-php-${{ matrix.php_version }}
                env:
                    CPU: ${{ matrix.cpu }}
                    USE_DEPOT: 1
                    DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}

            -   name: Test that layers can be exported
                run: |
                    make layer-php-${{ matrix.php_version }}
                    make layer-php-${{ matrix.php_version }}-fpm
                env:
                    CPU: ${{ matrix.cpu }}

            -   name: Test that the "console" layer can be exported
                run: make layer-console
                if: ${{ matrix.php_version == 80 }}
                env:
                    CPU: ${{ matrix.cpu }}

            -   name: Run tests
                run: make test-${{ matrix.php_version }}
                env:
                    CPU: ${{ matrix.cpu }}
