name: Tests

on:
    push:
        branches: [ 'main' ]
    pull_request:
        branches: [ '*' ]

jobs:
    tests-x86:
        name: Build and tests x86 layers
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php_version:
                    - 80
                    - 81
                    - 82
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up Docker buildx to use BuildKit features
                uses: docker/setup-buildx-action@v2
                with:
                    # Sets up `docker build` command as an alias to `docker buildx`
                    install: true
            -   name: Build Docker images
                uses: docker/bake-action@v2.3.0
                env:
                    PHP_VERSION: ${{ matrix.php_version }}
                    CPU: x86
                with:
                    # This is needed to make the built images available in later steps
                    # https://docs.docker.com/engine/reference/commandline/buildx_build/#load
                    load: true
                    # Cache Docker layers in GitHub Actions cache, scoped per image
                    # https://github.com/docker/bake-action/issues/87#issuecomment-1184659151
                    set: |
                        base-devel.cache-from=type=gha,scope=base-devel-x86
                        base-devel.cache-to=type=gha,scope=base-devel-x86,mode=max
                        build-php.cache-from=type=gha,scope=build-php-${{ matrix.php_version }}
                        build-php.cache-to=type=gha,scope=build-php-${{ matrix.php_version }},mode=max
                        php.cache-from=type=gha,scope=php-${{ matrix.php_version }}
                        php.cache-to=type=gha,scope=php-${{ matrix.php_version }},mode=max
                        php-fpm.cache-from=type=gha,scope=php-fpm-${{ matrix.php_version }}
                        php-fpm.cache-to=type=gha,scope=php-fpm-${{ matrix.php_version }},mode=max
                        fpm-internal-src.cache-from=type=gha,scope=fpm-internal-src-${{ matrix.php_version }}
                        fpm-internal-src.cache-to=type=gha,scope=fpm-internal-src-${{ matrix.php_version }},mode=max
                        console.cache-from=type=gha,scope=console-${{ matrix.php_version }}
                        console.cache-to=type=gha,scope=console-${{ matrix.php_version }},mode=max
                        php-fpm-dev.cache-from=type=gha,scope=php-fpm-dev-${{ matrix.php_version }}
                        php-fpm-dev.cache-to=type=gha,scope=php-fpm-dev-${{ matrix.php_version }},mode=max
            -   run: ls -lah tests
            -   run: cd tests && make test
            -   run: make -f cpu-x86.Makefile test

    tests-arm:
        name: Build ARM images, layers, and run tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            # See https://stackoverflow.com/questions/70312490/github-actions-runner-environment-doesnt-build-for-arm-images
            -   name: Set up QEMU to build ARM images
                uses: docker/setup-qemu-action@v2
            -   name: Set up Docker buildx to build ARM images
                uses: docker/setup-buildx-action@v2
            -   run: make -f cpu-arm.Makefile layers
            -   run: make -f cpu-arm.Makefile test
